@startuml
package simulateur.bateau{
class Bateau {
   - static int nombreDeBateauxConstruits
   - final String nom
   - Coque coque
   + static int getNombreDeBateauxConstruits()
   + Bateau(String nom)
   + void prendLaMer()
   + void navigue(double miles)
   + void arriveAuPort()
   + String getNom()
   + Coque getCoque()
   + void setCoque(Coque coque)
}

class BateauCivil extends Bateau{
   - int civil
}

class BateauMilitaire extends Bateau{
   - int forceCanon
   + Bateau(String nom)
   + int getForceCanon()
   + void setForceCanon(int forceCanon)
   + void attaque(Bateau cible)
}

package piece{
class Coque {
	- int pointsDeVie
	- int pointsDeVieMax
	+ Coque(int pointsDeVieMax)
	}
}
}
Bateau -> Coque
@enduml